version: '3'

services:
  php:
    container_name: php
    build: ./docker/php
    volumes:
    - ./server:/var/www

  nginx:
    image: nginx
    container_name: nginx
    ports:
    - 80:80
    volumes:
    - ./server:/var/www
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
    - php

  mariadb:
    container_name: laravel_mariadb
    build: ./docker/db
    image: laravel_mariadb
    ports:
      - 3306:3306
    volumes:
      - ./docker/db/data:/var/lib/mariadb
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root@1234